# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_modular_headers!


target 'FilterGroupViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # source '源地址'
  source 'https://github.com/CocoaPods/Specs.git'
  # Pods for FilterGroupViewDemo
  
   pod 'SnapKit'
   pod 'LEEAlert'
end

